### PR TITLE
Add htaccess rewrites for user-friendly urls.

### PR DESCRIPTION
**Pull request by aboutDavid**

### CODE REVIEW

**Comment by RiversideRocks** [comment]
Sorry I'm just getting to this, but I'm going to pass for now. I'm going to do a bit more work before I accept this.

**Comment by aboutDavid** [comment]
Oh I forgot to mention that I made sessions last a bit longer

**Comment by RiversideRocks** [comment]
I'll probably accept this, but will the old URL scheme work too?

**Comment by aboutDavid** [comment]
> I'll probably accept this, but will the old URL scheme work too?

Yes

**Comment by Stylix58** [comment]
PLEASE, MERGE THIS NOW!!!!!

**Pull request merged**
