### PR TITLE
Maybe don't pipe file file lol

### PR DESCRIPTION
**Pull request by aboutDavid**

### CODE REVIEW

**Comment by RiversideRocks** [comment]
Why not just use the date function with no args?

**Comment by RiversideRocks** [comment]
or put str() around date

**Comment by aboutDavid** [comment]
Well the thing is, piping won't send the file to the client

**Comment by RiversideRocks** [comment]
But my question is, where on earth does the file go when it isn't piped?

**Comment by aboutDavid** [comment]
> But my question is, where on earth does the file go when it isn't piped?

It's being echoed to the user

**Comment by RiversideRocks** [comment]
hmm ok ill see

**Pull request merged**
