### PR TITLE
Dump raw sql file

### PR DESCRIPTION
**Pull request by aboutDavid**

### CODE REVIEW

**Comment by RiversideRocks** [comment]
Hello, could you make it so that not all tables are dumped (just the reports table)? Maybe output it to a file?

**Comment by aboutDavid** [comment]
Yeah it's a good idea, I'll make changes when I get home

**Comment by aboutDavid** [comment]
Ok home now and everything is fixed.

**Comment by RiversideRocks** [comment]
Nice could you "pipe" it somewhere? (ie. mysql > file.sql)

**Comment by aboutDavid** [comment]
Ok done.

**Pull request merged**
