### PR TITLE
Add reference to Python API wrapper

### PR DESCRIPTION
**Pull request by Stylix58**

### CODE REVIEW

**Comment by Stylix58** [comment]
Please, see this, @RiversideRocks !!

**Comment by RiversideRocks** [comment]
I'll add it, but could you add docs to it?

**Comment by Stylix58** [comment]
in the future, yes!

**Comment by RiversideRocks** [comment]
Ok, well do post here when you add docs.

**Comment by Stylix58** [comment]
i have added the doc

**Pull request merged**
